#!/usr/bin/env perl

use FindBin;
BEGIN { unshift @INC, "$FindBin::Bin/../lib" }

use Import::Modern;
use Import::DB;

use Rose::DB::Object::Loader;
use Rose::DB::Object::ConventionManager;

my $loader = Rose::DB::Object::Loader->new(
    db           => Import::DB->new,
    class_prefix => 'Import::Model::',
    base_class   => 'Import::DB::Object',
);

# Удалим старые модели
use File::Path qw(remove_tree);
remove_tree("$FindBin::Bin/../lib/Import/Model", { keep_root => 1 });

# Сгенерируем новые модели
$loader->make_modules(module_dir => "$FindBin::Bin/../lib");
